## Makefile generalized
# Compiler and flags (overridable from environment)
CC ?= cc
CFLAGS ?= -Wall -Wextra -std=c11 -g
LDFLAGS ?=

# Source and build dirs (override if you want to use different layout)
SRC ?= src
OUT ?= dist

# Shared library extension and flags
SOEXT ?= so
SHARED_FLAGS ?= -shared -fPIC

# Install prefix
PREFIX ?= /usr/local
DESTDIR ?=

.PHONY: all clean install uninstall run

# Discover sources and map to object files in $(OUT)
SRCS := $(wildcard $(SRC)/*.c)
OBJS := $(patsubst $(SRC)/%.c,$(OUT)/%.o,$(SRCS))

# Default build: main and all plugin libs
LIBS := random player minmax
ALL_LIBS := $(patsubst %, $(OUT)/lib%.$(SOEXT), $(LIBS))

all: $(OUT)/main $(ALL_LIBS)

$(OUT)/main: $(OUT)/main.o $(OUT)/connectx.o | $(OUT)
	$(CC) $(LDFLAGS) $^ -o $@

# Generic rule: compile sources into $(OUT)/*.o
$(OUT)/%.o: $(SRC)/%.c | $(OUT)
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Generic rule: build shared plugin: libname.so <- name.o + connectx.o
$(OUT)/lib%.$(SOEXT): $(OUT)/%.o $(OUT)/connectx.o | $(OUT)
	$(CC) $(SHARED_FLAGS) $^ -o $@

$(OUT):
	mkdir -p $@

# Install/uninstall

install: all
	mkdir -p $(DESTDIR)$(PREFIX)/bin
	install -m 755 $(OUT)/main $(DESTDIR)$(PREFIX)/bin/
	mkdir -p $(DESTDIR)$(PREFIX)/lib
	install -m 755 $(ALL_LIBS) $(DESTDIR)$(PREFIX)/lib/

uninstall:
	rm -f $(DESTDIR)$(PREFIX)/bin/main
	rm -f $(patsubst %,$(DESTDIR)$(PREFIX)/lib/%,$(notdir $(ALL_LIBS)))

# Run the built executable. Pass arguments via ARGS, e.g. `make run ARGS="-v"`
# By default run a demo using the built plugins (random vs minmax)
ARGS ?= $(OUT)/libplayer.$(SOEXT) $(OUT)/libminmax.$(SOEXT)
run: all
	$(OUT)/main $(ARGS)

# Clean up build artifacts
clean:
	rm -rf $(OUT)

# Include dependency files generated by -MMD
-include $(OBJS:.o=.d)
