## Makefile generalized

# Enable OpenMP by default for parallel root-level search. Set OPENMP=0 to disable.
OPENMP ?= 1

# Compiler and flags (hardcoded for release/optimized builds)
CC := cc
CFLAGS := -Wall -Wextra -std=c11 -O3 -march=native -flto -DNDEBUG
LDFLAGS := -flto

ifeq ($(OPENMP),1)
CFLAGS += -fopenmp
LDFLAGS += -fopenmp
endif

# Build position-independent code for shared libraries and TLS safety
CFLAGS += -fPIC

# Source and build dirs (override if you want to use different layout)
SRC ?= src
OUT ?= dist

# Shared library extension and flags
SHARED_FLAGS ?= -shared -fPIC

# Install prefix
PREFIX ?= /usr/local
DESTDIR ?=


# Discover sources and map to object files in $(OUT)
SRCS := $(wildcard $(SRC)/*.c)
OBJS := $(patsubst $(SRC)/%.c,$(OUT)/%.o,$(SRCS))

# Default build: main and all plugin libs
LIBS := random player minmax
ALL_LIBS := $(patsubst %, $(OUT)/lib%.so, $(LIBS))

.PHONY: all clean run adb

all: $(OUT)/main $(ALL_LIBS)
adb: $(OUT)/adb-main $(ALL_LIBS)

$(OUT)/main: $(OUT)/main.o $(OUT)/connectx.o | $(OUT)
	$(CC) $(LDFLAGS) $^ -o $@

$(OUT)/adb-main: $(OUT)/adb-main.o $(OUT)/connectx.o | $(OUT)
	# adb build needs libpng for image control utilities
	$(CC) $(LDFLAGS) $^ -o $@ -lpng

# Generic rule: compile sources into $(OUT)/*.o
$(OUT)/%.o: $(SRC)/%.c | $(OUT)
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Generic rule: build shared plugin: libname.so <- name.o + connectx.o
$(OUT)/lib%.so: $(OUT)/%.o $(OUT)/connectx.o | $(OUT)
	$(CC) $(SHARED_FLAGS) $(LDFLAGS) $^ -o $@

$(OUT):
	mkdir -p $@

# Run the built executable. Pass arguments via ARGS, e.g. `make run ARGS="-v"`
# By default run a demo using the built plugins (random vs minmax)
ARGS ?= $(OUT)/libplayer.so $(OUT)/libminmax.so
run: all
	$(OUT)/main $(ARGS)

test: all
	$(OUT)/main $(OUT)/libminmax.so $(OUT)/libminmax.so

# Run the adb executable. Pass arguments via ADB_ARGS, e.g. `make adb-run ADB_ARGS="-v"`
ADB_ARGS ?= $(OUT)/libminmax.so
.PHONY: adb-run
adb-run: adb
	$(OUT)/adb-main $(ADB_ARGS)

# Clean up build artifacts
clean:
	rm -rf $(OUT)

# Include dependency files generated by -MMD
-include $(OBJS:.o=.d)
